"""Export executed command transcripts as .pml scripts."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

_command_log: List[str] = []
_last_export_path: Optional[Path] = None


def reset_log() -> None:
    global _command_log
    _command_log = []


def append_commands(commands: List[str]) -> None:
    for c in commands:
        c = c.strip()
        if c and (not _command_log or _command_log[-1] != c):
            _command_log.append(c)


def get_log() -> List[str]:
    return list(_command_log)


def export_pml(path: Optional[str] = None, header: str = "") -> Path:
    global _last_export_path
    if path:
        out = Path(path).expanduser()
    else:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        out = Path.cwd() / f"pymollm_{stamp}.pml"
    lines = [
        "# Generated by pymollm",
        f"# {datetime.now(timezone.utc).isoformat()}",
    ]
    if header:
        for hline in header.strip().splitlines():
            lines.append(f"# {hline}")
    lines.append("")
    lines.extend(_command_log or ["# (no commands recorded)"])
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    _last_export_path = out
    return out


def last_export_path() -> Optional[Path]:
    return _last_export_path
